### ISSUE TITLE
apply process does not work

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-odc#5]
The apply process does not work, because it is handled in the same way as a reduce_dimension, but apply doesn't have the dimension keyword, see here https://github.com/Open-EO/openeo-odc/blob/master/src/openeo_odc/map_to_odc.py#L22

**Comment by clausmichele** [comment]
The problem is that there is no apply implemented in openeo-processes-python https://github.com/Open-EO/openeo-processes-python/issues/23

**Comment by clausmichele** [comment]
Solved with those two pull requests_
https://github.com/Open-EO/openeo-odc/pull/6
https://github.com/Open-EO/openeo-processes-python/pull/24

**Comment by clausmichele** [comment]
Apply is still not usable, the mapping of the parameters for processes inside apply does not work.

**Comment by sophieherrmann** [comment]
Fixed with https://github.com/Open-EO/openeo-odc/pull/11
